package com.imageuploader;

import android.graphics.Bitmap;
import android.os.AsyncTask;
import android.os.Environment;
import android.provider.MediaStore;
import android.support.v7.app.AppCompatActivity;
import android.os.Bundle;
import android.util.Log;
import android.widget.Toast;

import com.nostra13.universalimageloader.core.ImageLoader;
import com.nostra13.universalimageloader.core.ImageLoaderConfiguration;

import java.io.BufferedOutputStream;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.List;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        ImageLoaderConfiguration config = new ImageLoaderConfiguration.Builder(this).build();
        ImageLoader.getInstance().init(config);

        setContentView(R.layout.activity_main);


        new loadimage().execute();


/*
        String[] skus = {"WY4560",
                "WHY4190",
                "WHD5650",
                "VTX2550",
                "UWP1234",
                "UWP123",
                "UNGF12",
                "UMJ123",
                "UMJ12",
                "UMH12",
                "UIS1234",
                "UIS123",
                "UGP123",
                "UBCAA1",
                "TWAML12",
                "TOTPRO4550",
                "TM5500",
                "TLWP12",
                "TLSMG1",
                "testing_image-3 lbs",
                "testing_image",
                "test-1",
                "Test Products test",
                "test product",
                "T323A",
                "T-212A",
                "SYN65000",
                "SYN5LBS6250",
                "SYBAG9200",
                "SXIWK1",
                "SUMG3350",
                "STAK3250",
                "SSNPW2",
                "SSNPW1",
                "SSNP13",
                "SSNP12",
                "SSNCM1",
                "SSNCF2",
                "SSNCF1",
                "SSNAMB1",
                "SSNAG1",
                "SSNAB1",
                "SMGB5110",
                "SHDF3000",
                "RL602330",
                "RBMPB20",
                "RBMP10",
                "PW502000",
                "PSH30S",
                "PMCPW1",
                "PHPRG1",
                "OYWP12",
                "ONZMA12",
                "ONWP35",
                "ONWP234",
                "ONWP23",
                "ONWP12",
                "ONTB12",
                "ONSM123",
                "ONSM12",
                "ONSA2222",
                "ONPHB12",
                "ONOTM12",
                "ONMCP12",
                "ONGSPW1",
                "ONGM123",
                "one-whey-lbs",
                "ONAE12",
                "NWOM1234",
                "NWOM123",
                "NWMN12",
                "NWLG12",
                "NWLDR12",
                "NWLA12",
                "NWCP12",
                "NTO312",
                "NTMI123",
                "NTMI12",
                "NTLPH12",
                "NTLPG12",
                "NTLPBM1",
                "NTLC123",
                "NTLC12",
                "NTLBUC1",
                "NTHRB12",
                "NRPEN07",
                "NRPEN06",
                "NRPEN05",
                "NRPEN04",
                "NRPEN03",
                "NRPEN02",
                "NRPEN01",
                "NOXP2650",
                "NO1202300",
                "NMSC123",
                "NI90TAB2100",
                "NBMT12",
                "NBIP1234",
                "NBIP123",
                "NBIP12",
                "NBDH12",
                "NBCP12",
                "MTWP12",
                "MTPMV12",
                "MTPH212",
                "MTPH12",
                "MTPFO12",
                "MTPC95",
                "MTNT12",
                "MTNC30",
                "MTMT123",
                "MTMG12",
                "MTLC12",
                "MTHCW12",
                "MTHC12",
                "MTGM12",
                "MTCT12",
                "MTAC30",
                "MS2960",
                "MRPW2590",
                "MPZMA32",
                "MPSM54",
                "MPLC25",
                "MPIPW56",
                "MPIP30S",
                "MPG256",
                "MPCP126",
                "MPCLA5",
                "MPBCAAP2",
                "MPBCAA312",
                "MPASS32",
                "MPAP32",
                "MPAP15S",
                "MPAFB90",
                "MMNB123",
                "MMG124990",
                "MMCP123",
                "MMCM125",
                "MMCBA12",
                "MMAD123",
                "MM5LBS3200",
                "MLC4567",
                "MFB2780",
                "MDCPB12",
                "MB11lbs5200",
                "MA4LBS4750",
                "LPR5550",
                "LNINE2000",
                "lbs2",
                "lbs1",
                "LBS",
                "IT-213A",
                "IT-211A",
                "ISOSEN93",
                "ISO5LBS6500",
                "IGF24350",
                "Hr-8Tm",
                "HPT-321A",
                "HPT-320",
                "HPRFX2300",
                "HP-353A",
                "Hp352A",
                "Hp351A",
                "hp350A",
                "HP-322",
                "HP-210A",
                "Hp12A",
                "HMG15LBS5350",
                "HG5LBS2890",
                "HG3200",
                "GINE1950",
                "GAIN4350",
                "G25LBS4550",
                "FP10LBS7549",
                "ELP2LBS3500",
                "EL5LBS5250",
                "D45500",
                "CWFB2650",
                "CWB1850",
                "CT-512",
                "CT 500 JS",
                "CMJ120D",
                "CMJ100",
                "CLA2250",
                "CELL3100",
                "CDJ240",
                "C991MS",
                "C991ES",
                "C4WORK2550",
                "BS1001900",
                "B-Nox24",
                "BMF2450",
                "BCA2550",
                "BAPW2220",
                "ANOX2350",
                "AML2300",
                "AM3602350",
                "AM21867",
                "AG15LBS5800",
                "704-COLOR",
                "50SER2500",
                "1MRPO2000",
                " CT300J",
                "455",
                "111"};
        String[] urls = {"http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_amino_x.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/j/a/jack_3d-_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_vortex.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_blox_amino_pre-workout_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-nutrition-prostar-100-whey-protein-natural.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-whey_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/u/n/universal-gain_fast-_5_lbd.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mj_10lb.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mj_2lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mono.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-iso_2lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate_isosensation_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-gluta_pure.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-bcaa.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-amino_fuel.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/o/cobra_labs-_the_curse-2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_no_xplode.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-protein_1lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-gainer_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/9/_/9.png",
                "http://www.mauryamegamart.com/media/catalog/product/c/h/chrysanthemum.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/0/9/094b32163815becb51bc260682c344ccplp-w-newarrivals_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/ce323a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/212a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha_isolate_4_lbs_1.png",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha-6-2.27_kg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_1mr_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/c/sciavation.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_super-mass_gainer-12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_stak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-performance_whey_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ss-p2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-2lb.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/r/prd_78240_c_xxl.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-carbo-force_10lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-carbo_force.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-ambl.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-anabolic_builder1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/y/cytosport_muscle_milk.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_c-4_60_serving.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/p/apn_muscle_boost_5000.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/p/r/prd_47115_c_m.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/innovative-_black_mamba_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/s/ps-mr.hyde_30ser..jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/o/con-cret1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/h/php-_mass_gainer.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/h/oh_y-_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-zma.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-_hey_5_lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-8lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/onwhey_2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-5lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on_tribulus.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-_serious_mass_6lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-serious_mass_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on_amino2222.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/p/optimum-hydro-builder-banner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-opti_men.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-creatine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-glutamine_powder.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-5lbs_1_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-amino_energy.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_omega-3-6-9.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_omega-3.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_amino_500mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_l-glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_liver_detoxifier_and_regenerator.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-l-arginine.jpeg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_chromium_picolinate.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/natrol-_omega_3-6-9_complex_fish_oil.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-muscle_infusion_black_2-lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-muscle_infusion_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex_lipo-6_hers_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-lipo-6_hers_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/i/lipo-6.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_carnitine.png",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_caffeine.png",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_ultra_concentrate_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_hemorage.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/u/luxor_hi_techpoint_v10.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/9/0/9000000540_2__41380_zoom-600x600.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/v/-/v-signpen.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/i/pilot-hi-techpoint-v7-rt-sdl813520528-1-7f0d1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/v/r/vrt5.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/i/pilot-hi-tecpoint-v5-grip-roller-ball-pen-0-a117707.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/u/luxor-801-pilot-hi-techpoint-05-pen.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_hyper_fx.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix-fusion_protein_2300g_1403_l_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/natural_max-_slimming_capsules.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_amino_x_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_milk_thistle_1000mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_7.5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_3.5_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_3lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_dhea_25mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_chromium_picolinate_200mcg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_whey_protein_bag.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_multi-vitamin_90_tablets.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_phase-8_2_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_phase-8_4.46_lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musletech-_fish_oil.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_cla_95.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_nitrotech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musletech-neurocore.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_mass_tech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_mass_gainer_12lbs_bag.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_carnitine_180_cap.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_hydroxycut_fat_burner_for_women.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_hydroxycut_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_celltech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-anarchy_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_m_stak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_hard_gainer_5lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_z-core.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_shread_matrix.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_l-cartinine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_pump_whey.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_pump_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_combat_powder_new_pack_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_cla.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_bcaa_powder.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_bcaa_3_1_2_cap.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_assault.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_amino_powder_32.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_amino_powder_15ser.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_cut.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_no_bull_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/j/_/j_cutler-_whey_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/_/m_m-_carbo_max.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_beef_amino.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musclemeds-amino_decanate.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/u/cutler-_total_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/matrix-_l-cartinine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-black_spider.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_8_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix_nitric_oxide_120cps_1_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_amino_6000.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_muscle_mass_gainer_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/matrix-_cla_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/o/download.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/8/1/815jqdn3wwl._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/6/1/61n5heyddbl._sy355__1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/213a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/211a.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_bcaa.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_pak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/m/imageservice.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/7/1/71hr8d1m_1l._sx522_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/0/c02977049.png",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha_isolate_4_lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/353a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/a/data-zc-foto-575-01-2-600x600.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/351a.png",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/350a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/ce322a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/210a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/h/p/hp_12a_toner__16376.1437399788.1280.1280.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_anabolic_peak_gainer_15lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/h/y/hyper_gain-_gainer.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_lean_pro_8.png",
                "http://www.mauryamegamart.com/media/catalog/product/g/a/gaspari_nutrition-_myofusion_advance_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/g/a/gaspari_nutrition-_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_humano_growth.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/an_igf-2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_elite_protein_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_super_mass_gainer_chocolate_6-lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_super_hd_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_whey_protein_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-_asia_black_fat_burner_100_capsules.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/5/1/51hpa2pa1ll._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/8/1/81c6dhkr12l._sy450_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/a/casio-indotama-shop_casio-mj-120d-two-way-power-kalkulator-12-digit_full01.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/j/mj-100d.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/mammoth-_gainer_2500.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_nitrix_90_capsules.jpeg",
                "http://www.mauryamegamart.com/media/catalog/product/d/j/dj-240d_plus_560.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/a/casio-fx-991ms-l33tness.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/f/x/fx-991es_plus_we_f1_2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_cell_mass_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma_-china_white.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/1/7/1756246_set.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_whey_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_elite_protein_2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_roxy_lean_60_capsules_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_true_mass_2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_iso_100_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_hard_mass_gainer_15lbs_1.png",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix-fusion_protein_2300g_1403_l.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_muscle_rush_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-methyldrene.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_whey_hd.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/t/ct-300j.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/6/1/61n5heyddbl._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/c/school.jpeg"};




        ImageLoader imageLoader = ImageLoader.getInstance();






        for(int i = 0 ; i< urls.length ; i++)
        {
            Bitmap bitmap = imageLoader.loadImageSync(urls[i]);
            String path = Environment.getExternalStorageDirectory().toString();
            OutputStream fOutputStream = null;
            File file = new File(path + "/Captures/", skus[i] +".jpg");
            if (!file.exists()) {
                file.mkdirs();
            }

            try {
                fOutputStream = new FileOutputStream(file);

                bitmap.compress(Bitmap.CompressFormat.JPEG, 100, fOutputStream);

                fOutputStream.flush();
                fOutputStream.close();

                MediaStore.Images.Media.insertImage(getContentResolver(), file.getAbsolutePath(), file.getName(), file.getName());

                Log.d(String.valueOf(i) , "done");
            } catch (FileNotFoundException e) {
                e.printStackTrace();


                //Toast.makeText(this, "Save Failed", Toast.LENGTH_SHORT).show();
                return;
            } catch (IOException e) {
                e.printStackTrace();
                Toast.makeText(this, "Save Failed", Toast.LENGTH_SHORT).show();
                return;
            }

        }


*/







    }

    public class loadimage extends AsyncTask<Void , Void , Void>
    {
        String[] skus = {"WY4560",
                "WHY4190",
                "WHD5650",
                "VTX2550",
                "UWP1234",
                "UWP123",
                "UNGF12",
                "UMJ123",
                "UMJ12",
                "UMH12",
                "UIS1234",
                "UIS123",
                "UGP123",
                "UBCAA1",
                "TWAML12",
                "TOTPRO4550",
                "TM5500",
                "TLWP12",
                "TLSMG1",
                "testing_image-3 lbs",
                "testing_image",
                "test-1",
                "Test Products test",
                "test product",
                "T323A",
                "T-212A",
                "SYN65000",
                "SYN5LBS6250",
                "SYBAG9200",
                "SXIWK1",
                "SUMG3350",
                "STAK3250",
                "SSNPW2",
                "SSNPW1",
                "SSNP13",
                "SSNP12",
                "SSNCM1",
                "SSNCF2",
                "SSNCF1",
                "SSNAMB1",
                "SSNAG1",
                "SSNAB1",
                "SMGB5110",
                "SHDF3000",
                "RL602330",
                "RBMPB20",
                "RBMP10",
                "PW502000",
                "PSH30S",
                "PMCPW1",
                "PHPRG1",
                "OYWP12",
                "ONZMA12",
                "ONWP35",
                "ONWP234",
                "ONWP23",
                "ONWP12",
                "ONTB12",
                "ONSM123",
                "ONSM12",
                "ONSA2222",
                "ONPHB12",
                "ONOTM12",
                "ONMCP12",
                "ONGSPW1",
                "ONGM123",
                "one-whey-lbs",
                "ONAE12",
                "NWOM1234",
                "NWOM123",
                "NWMN12",
                "NWLG12",
                "NWLDR12",
                "NWLA12",
                "NWCP12",
                "NTO312",
                "NTMI123",
                "NTMI12",
                "NTLPH12",
                "NTLPG12",
                "NTLPBM1",
                "NTLC123",
                "NTLC12",
                "NTLBUC1",
                "NTHRB12",
                "NRPEN07",
                "NRPEN06",
                "NRPEN05",
                "NRPEN04",
                "NRPEN03",
                "NRPEN02",
                "NRPEN01",
                "NOXP2650",
                "NO1202300",
                "NMSC123",
                "NI90TAB2100",
                "NBMT12",
                "NBIP1234",
                "NBIP123",
                "NBIP12",
                "NBDH12",
                "NBCP12",
                "MTWP12",
                "MTPMV12",
                "MTPH212",
                "MTPH12",
                "MTPFO12",
                "MTPC95",
                "MTNT12",
                "MTNC30",
                "MTMT123",
                "MTMG12",
                "MTLC12",
                "MTHCW12",
                "MTHC12",
                "MTGM12",
                "MTCT12",
                "MTAC30",
                "MS2960",
                "MRPW2590",
                "MPZMA32",
                "MPSM54",
                "MPLC25",
                "MPIPW56",
                "MPIP30S",
                "MPG256",
                "MPCP126",
                "MPCLA5",
                "MPBCAAP2",
                "MPBCAA312",
                "MPASS32",
                "MPAP32",
                "MPAP15S",
                "MPAFB90",
                "MMNB123",
                "MMG124990",
                "MMCP123",
                "MMCM125",
                "MMCBA12",
                "MMAD123",
                "MM5LBS3200",
                "MLC4567",
                "MFB2780",
                "MDCPB12",
                "MB11lbs5200",
                "MA4LBS4750",
                "LPR5550",
                "LNINE2000",
                "lbs2",
                "lbs1",
                "LBS",
                "IT-213A",
                "IT-211A",
                "ISOSEN93",
                "ISO5LBS6500",
                "IGF24350",
                "Hr-8Tm",
                "HPT-321A",
                "HPT-320",
                "HPRFX2300",
                "HP-353A",
                "Hp352A",
                "Hp351A",
                "hp350A",
                "HP-322",
                "HP-210A",
                "Hp12A",
                "HMG15LBS5350",
                "HG5LBS2890",
                "HG3200",
                "GINE1950",
                "GAIN4350",
                "G25LBS4550",
                "FP10LBS7549",
                "ELP2LBS3500",
                "EL5LBS5250",
                "D45500",
                "CWFB2650",
                "CWB1850",
                "CT-512",
                "CT 500 JS",
                "CMJ120D",
                "CMJ100",
                "CLA2250",
                "CELL3100",
                "CDJ240",
                "C991MS",
                "C991ES",
                "C4WORK2550",
                "BS1001900",
                "B-Nox24",
                "BMF2450",
                "BCA2550",
                "BAPW2220",
                "ANOX2350",
                "AML2300",
                "AM3602350",
                "AM21867",
                "AG15LBS5800",
                "704-COLOR",
                "50SER2500",
                "1MRPO2000",
                " CT300J",
                "455",
                "111"};
        String[] urls = {"http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_amino_x.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/j/a/jack_3d-_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_vortex.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_blox_amino_pre-workout_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-nutrition-prostar-100-whey-protein-natural.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-whey_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/u/n/universal-gain_fast-_5_lbd.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mj_10lb.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mj_2lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-mono.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-iso_2lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate_isosensation_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-gluta_pure.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/u/l/ultimate-bcaa.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-amino_fuel.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/o/cobra_labs-_the_curse-2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_no_xplode.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-protein_1lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/t/w/twinlab-gainer_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/9/_/9.png",
                "http://www.mauryamegamart.com/media/catalog/product/c/h/chrysanthemum.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/0/9/094b32163815becb51bc260682c344ccplp-w-newarrivals_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/ce323a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/212a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha_isolate_4_lbs_1.png",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha-6-2.27_kg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_1mr_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/c/sciavation.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_super-mass_gainer-12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_stak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-performance_whey_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ss-p2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-2lb.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/r/prd_78240_c_xxl.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-carbo-force_10lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-carbo_force.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-ambl.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/s/ssn-anabolic_builder1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/y/cytosport_muscle_milk.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_c-4_60_serving.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/p/apn_muscle_boost_5000.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/p/r/prd_47115_c_m.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/innovative-_black_mamba_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/s/ps-mr.hyde_30ser..jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/o/con-cret1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/h/php-_mass_gainer.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/h/oh_y-_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-zma.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-_hey_5_lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-8lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/onwhey_2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-5lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on_tribulus.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-_serious_mass_6lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-serious_mass_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on_amino2222.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/p/optimum-hydro-builder-banner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-opti_men.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-creatine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-glutamine_powder.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-5lbs_1_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/o/n/on-amino_energy.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_omega-3-6-9.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_omega-3.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_amino_500mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_l-glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_liver_detoxifier_and_regenerator.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-l-arginine.jpeg",
                "http://www.mauryamegamart.com/media/catalog/product/n/o/now-_chromium_picolinate.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/natrol-_omega_3-6-9_complex_fish_oil.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-muscle_infusion_black_2-lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-muscle_infusion_5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex_lipo-6_hers_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-lipo-6_hers_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/i/lipo-6.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_carnitine.png",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_caffeine.png",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_lipo-6_ultra_concentrate_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/u/nutrex-_hemorage.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/u/luxor_hi_techpoint_v10.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/9/0/9000000540_2__41380_zoom-600x600.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/v/-/v-signpen.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/i/pilot-hi-techpoint-v7-rt-sdl813520528-1-7f0d1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/v/r/vrt5.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/p/i/pilot-hi-tecpoint-v5-grip-roller-ball-pen-0-a117707.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/u/luxor-801-pilot-hi-techpoint-05-pen.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_hyper_fx.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix-fusion_protein_2300g_1403_l_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/natural_max-_slimming_capsules.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_amino_x_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_milk_thistle_1000mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_7.5lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_3.5_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_best-_iso_pure_3lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_dhea_25mg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/n/a/nature_s_bounty-_chromium_picolinate_200mcg.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_whey_protein_bag.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_multi-vitamin_90_tablets.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_phase-8_2_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_phase-8_4.46_lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musletech-_fish_oil.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_cla_95.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_nitrotech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musletech-neurocore.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_mass_tech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_mass_gainer_12lbs_bag.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_carnitine_180_cap.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_hydroxycut_fat_burner_for_women.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_hydroxycut_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_platinum_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-_celltech.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscletech-anarchy_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_m_stak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_hard_gainer_5lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_z-core.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_shread_matrix.png",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_l-cartinine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_pump_whey.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_pump_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_combat_powder_new_pack_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_cla.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_bcaa_powder.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_bcaa_3_1_2_cap.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_assault.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_amino_powder_32.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_amino_powder_15ser.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_pharma-_arnold_iron_cut.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_no_bull_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/j/_/j_cutler-_whey_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/_/m_m-_carbo_max.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_beef_amino.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/musclemeds-amino_decanate.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/u/cutler-_total_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/matrix-_l-cartinine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-black_spider.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/u/muscle_meds-_carnivor_8_lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix_nitric_oxide_120cps_1_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_amino_6000.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_muscle_mass_gainer_12lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/matrix-_cla_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/o/download.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/8/1/815jqdn3wwl._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/6/1/61n5heyddbl._sy355__1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/213a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/211a.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_bcaa.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/animal_pak.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/m/imageservice.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/7/1/71hr8d1m_1l._sx522_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/0/c02977049.png",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn-syntha_isolate_4_lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/353a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/a/data-zc-foto-575-01-2-600x600.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/351a.png",
                "http://www.mauryamegamart.com/media/catalog/product/3/5/350a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/ce322a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/2/1/210a.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/h/p/hp_12a_toner__16376.1437399788.1280.1280.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_anabolic_peak_gainer_15lbs_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/h/y/hyper_gain-_gainer.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_lean_pro_8.png",
                "http://www.mauryamegamart.com/media/catalog/product/g/a/gaspari_nutrition-_myofusion_advance_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/g/a/gaspari_nutrition-_glutamine.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/l/a/labrada-_humano_growth.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/a/n/an_igf-2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_elite_protein_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_super_mass_gainer_chocolate_6-lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_super_hd_fat_burner.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/e/cellucor-_whey_protein_4lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-_asia_black_fat_burner_100_capsules.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/5/1/51hpa2pa1ll._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/8/1/81c6dhkr12l._sy450_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/a/casio-indotama-shop_casio-mj-120d-two-way-power-kalkulator-12-digit_full01.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/j/mj-100d.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/m/a/mammoth-_gainer_2500.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_nitrix_90_capsules.jpeg",
                "http://www.mauryamegamart.com/media/catalog/product/d/j/dj-240d_plus_560.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/a/casio-fx-991ms-l33tness.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/f/x/fx-991es_plus_we_f1_2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_cell_mass_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma_-china_white.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/1/7/1756246_set.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_whey_protein.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_elite_protein_2lbs.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_roxy_lean_60_capsules_1.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/s/bsn_true_mass_2.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/d/y/dymatize-_iso_100_5lbs.png",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_hard_mass_gainer_15lbs_1.png",
                "http://www.mauryamegamart.com/media/catalog/product/a/m/amix-fusion_protein_2300g_1403_l.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/i/n/inner_armour-_muscle_rush_pre-workout.jpg",
                "http://www.mauryamegamart.com/media/catalog/productno_selection",
                "http://www.mauryamegamart.com/media/catalog/product/c/l/cloma_pharma-methyldrene.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/b/p/bpi_whey_hd.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/c/t/ct-300j.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/6/1/61n5heyddbl._sy355_.jpg",
                "http://www.mauryamegamart.com/media/catalog/product/s/c/school.jpeg"};


        @Override
        protected Void doInBackground(Void... voids) {


            ImageLoader imageLoader = ImageLoader.getInstance();


            Log.d("asdasdads", "started");


            for (int i = 0; i < urls.length; i++) {

try
{
    Bitmap bitmap = imageLoader.loadImageSync(urls[i]);

    Log.d(String.valueOf(i) , urls[i]);

    storeImage(bitmap, skus[i]);
}catch (Exception e)
{
    e.printStackTrace();
}



            }


            return null;
        }

    }


    private boolean storeImage(Bitmap imageData, String filename) {
        //get path to external storage (SD card)
        String iconsStoragePath = Environment.getExternalStorageDirectory() + "/myAppDir/myImages/";
        File sdIconStorageDir = new File(iconsStoragePath);

        //create storage directories, if they don't exist
        sdIconStorageDir.mkdirs();

        try {
            String filePath = sdIconStorageDir.getAbsolutePath()+"/" + filename+".png";
            FileOutputStream fileOutputStream = new FileOutputStream(filePath);

            BufferedOutputStream bos = new BufferedOutputStream(fileOutputStream);

            //choose another format if PNG doesn't suit you
            imageData.compress(Bitmap.CompressFormat.PNG, 100, bos);

            bos.flush();
            bos.close();

        } catch (FileNotFoundException e) {
            Log.w("TAG", "Error saving image file: " + e.getMessage());
            return false;
        } catch (IOException e) {
            Log.w("TAG", "Error saving image file: " + e.getMessage());
            return false;
        }

        return true;
    }



}
